config/routes.rb
Rails.application.routes.draw do
  get 'blog_page/index'
  get 'blog_page/about'
  get 'blog_page/contact'
  resources :articles
  root 'blog_page#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :author, :image_url, :body)
    end
end

app/controllers/blog_page_controller.rb
class BlogPageController < ApplicationController
  def index
    @articles = Article.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blog_page_helper.rb
module BlogPageHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Image url</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.author %></td>
        <td><%= article.image_url %></td>
        <td><%= article.body %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>


<h3><%= @article.title %></h3>


<p>
  <strong>Author:</strong>
  <%= @article.author %>
  <br>
  published on <%= @article.created_at.strftime("%b %d, %Y") %><br>
</p>
<br>
<p>
  <%= image_tag(@article.image_url) %>
</p>
<br>
<p>
  <%= @article.body %>
</p>
<br>

<div class="article-control">
  <%= link_to 'Back', root_path %>
</div>

app/views/blog_page/about.html.erb
<h2>about - WebDev</h2>
<p>want to get to know us? great!</p>
<p>info about our team coming soon</p>

app/views/blog_page/contact.html.erb
<h2>contact us - WebDev</h2>
<p>do you have some questions about our content? dying to get in touch with us?</p>
<p><span class="glyphicon glyphicon-envelope"></span> info@webdev.blog</p>
<p><span class="glyphicon glyphicon-earphone"></span> (049)1234 56 789</p>

<p>we will get back to you as soon as possible!</p>

app/views/blog_page/index.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <h2><b><%= article.title %></b></h2><br>
    <p>by <%= article.author %><br>
    published on <%= article.created_at.strftime("%b %d, %Y") %></p><br>
    <%= image_tag(article.image_url, class: "img-responsive") %><br>
    <%= article.body %><br>
    <br>
    <%= link_to 'click to view', article %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebDev blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>


  <body>
    <nav class="navbar sticky-top navbar-light bg-light">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#blogNav">
              <span class="icon-bar glyphicon glyphicon-list"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
          <p id="brand-logo"><%= link_to "WebDev", root_path %></p>
        </div> <!-- end header -->
        <div class="collapse navbar-collapse navbar-right" id="blogNav">
          <ul class="nav navbar-nav">
            <li><%= link_to "home", root_path %></li>
            <li><%= link_to "about", blog_page_about_path %></li>
            <li><%= link_to "contact", blog_page_contact_path %></li>
          </ul>
          </div>
        </div> <!-- end container -->
    </nav>

    <%= image_tag("banner03.jpg", class:"img-responsive", id:"banner") %>

    <%= yield %>

    <footer>
      <p>&copy; WebDev 2018</p>
    </footer>

  </body>

</html>